/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.3 and Signal Processing Toolbox 7.5.
 * Generated on: 06-Jun-2021 16:05:50
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 2
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */

/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2017b\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int32 filter coefficients.
 */
#define MWSPT_NSEC 5
const int NL[MWSPT_NSEC] = { 1,3,1,3,1 };
const int32_T NUM[MWSPT_NSEC][3] = {
  {
    1061618021,           0,           0 
  },
  {
    2147483647,           0, -2147483648 
  },
  {
    1061618021,           0,           0 
  },
  {
    2147483647,           0, -2147483648 
  },
  {
    1913946816,           0,           0 
  }
};
const int DL[MWSPT_NSEC] = { 1,3,1,3,1 };
const int32_T DEN[MWSPT_NSEC][3] = {
  {
    2147483647,           0,           0 
  },
  {
    2147483647, -2147483648,  2146141034 
  },
  {
    2147483647,           0,           0 
  },
  {
    2147483647,  -755357381,   708540941 
  },
  {
    2147483647,           0,           0 
  }
};
